language: node_js
node_js:
 — “7”
script:
 — echo “Deploy!!”
install:
 — npm install -g firebase-tools
after_success:
 — lint
 — firebase deploy — project project-896179650864
 — token 1/swaFjiL6Cl-a-Zbo5GlOrjPysghWSRjLSrmMkwa7jDA